/**
 * The audit action registry. Every state-changing operation in the system appears here.
 *
 * Key format: `<entity>.<action>`. The label is what the Auditoría screen and its filter
 * dropdown show. Safe to import from the browser: data only.
 *
 * ADDING A CRUD OPERATION? Add its actions here in the same change that adds the
 * operation — see CLAUDE.md Rule 3. An unregistered action still records fine, it just
 * renders as its raw key and cannot be picked from the filter.
 */
export const AUDIT_ACTIONS = {
	"user.role_change": "Cambio de rol",
	"user.ban": "Usuario bloqueado",
	"user.unban": "Usuario desbloqueado",
	"user.impersonate_start": "Impersonación iniciada",
	"user.impersonate_stop": "Impersonación terminada",
	"invitation.create": "Invitación creada",
	"invitation.revoke": "Invitación revocada",
	"invitation.accept": "Invitación aceptada",
	"cliente.create": "Cliente creado",
	"cliente.update": "Cliente actualizado",
	"cliente.archive": "Cliente archivado",
	"cliente.restore": "Cliente restaurado",
	"cliente.delete": "Cliente eliminado",
	"cliente.merge": "Cliente fusionado con otro",
	"contacto.create": "Contacto creado",
	"contacto.update": "Contacto actualizado",
	"contacto.delete": "Contacto eliminado",
	"telefono.create": "Teléfono agregado",
	"telefono.update": "Teléfono actualizado",
	"telefono.delete": "Teléfono eliminado",
	"telefono.principal": "Teléfono marcado como principal",
	"unidad.create": "Unidad creada",
	"unidad.update": "Unidad actualizada",
	"unidad.archive": "Unidad archivada",
	"unidad.restore": "Unidad restaurada",
	"unidad.delete": "Unidad eliminada",
	"unidad.transfer": "Unidad transferida",
	"unidad.merge": "Unidad fusionada con otra",
	// The public form. Recorded with a null actor — see recordAudit.
	"cita.solicitud": "Cita solicitada (público)",
	"cita.create": "Cita creada",
	"cita.link": "Cita vinculada a cliente y unidad",
	"cita.hora": "Hora asignada a una cita",
	"cita.update": "Cita actualizada",
	"cita.confirm": "Cita confirmada",
	"cita.assign": "Cita asignada",
	"cita.advance": "Cita avanzada",
	"cita.cancel": "Cita cancelada",
	"cita.receive": "Unidad recibida (nota abierta)",
	"nota.create": "Nota de servicio abierta",
	"nota.update": "Nota de servicio actualizada",
	"nota.inspect": "Inspección de entrada",
	"nota.advance": "Nota avanzada",
	"nota.transfer": "Nota enviada a taller",
	"nota.return": "Nota devuelta del taller",
	"nota.qa": "Control de calidad al regresar del taller",
	"nota.comment": "Comentario en nota",
	"nota.evidence": "Evidencia adjuntada",
	"nota.evidence_delete": "Evidencia eliminada",
	"nota.close": "Nota entregada y cerrada",
	"nota.cancel": "Nota cancelada",
	"nota.liberacion": "Checklist de liberación guardado",
	"nota.reporte_ia": "Reporte generado con IA",
	"proveedor.create": "Proveedor creado",
	"proveedor.editar": "Proveedor actualizado",
	"proveedor.compra": "Compra registrada a proveedor",
	"recordatorio.create": "Recordatorio creado",
	"recordatorio.hecho": "Recordatorio marcado",
	"taller.create": "Taller aliado dado de alta",
	"taller.update": "Taller aliado actualizado",
	"taller.archive": "Taller aliado archivado",
	// The public /talleres application. Recorded with a null actor, same as cita.solicitud.
	"taller.solicitud": "Taller solicitó certificarse (público)",
	"taller.approve": "Taller certificado",
	"taller.reject": "Solicitud de taller rechazada",
	"taller.mecanico": "Mecánico asignado a un taller aliado",
	"sucursal.create": "Sucursal de taller creada",
	"sucursal.update": "Sucursal de taller actualizada",
	"sucursal.archive": "Sucursal de taller archivada",
	"producto.create": "Producto dado de alta",
	"producto.update": "Producto actualizado",
	"producto.archive": "Producto archivado",
	"inventario.entrada": "Entrada de mercancía",
	"inventario.ajuste": "Ajuste de existencia",
	"refaccion.solicitud": "Refacción solicitada",
	"refaccion.surtida": "Refacción surtida",
	"refaccion.rechazada": "Refacción no disponible",
	"cotizacion.interno": "Avance interno de cotización",
	"cotizacion.concepto": "Conceptos de cotización actualizados",
	"nota.mecanico": "Mecánico asignado",
	"nota.diagnostico": "Diagnóstico capturado",
	"nota.trabajo": "Trabajo del mecánico terminado",
	"notificacion.send": "Aviso enviado a mano",
	"notificacion.preferencias": "Preferencias de avisos actualizadas",
	"push.subscribe": "Dispositivo registrado para avisos",
	"push.unsubscribe": "Dispositivo dado de baja de avisos",
	"nota.seguimiento": "Liga de seguimiento regenerada",
	"unidad.kilometraje": "Kilometraje registrado",
	"cotizacion.create": "Cotización creada",
	"cotizacion.update": "Cotización actualizada",
	"cotizacion.send": "Cotización enviada al cliente",
	"cotizacion.reenviar": "Correo de cotización reenviado",
	"cotizacion.authorize": "Cotización autorizada por el cliente",
	"cotizacion.reject": "Cotización rechazada",
	"cotizacion_interna.create": "Estimación de costo creada",
	"cotizacion_interna.update": "Estimación de costo actualizada",
	"cotizacion_interna.vincular": "Estimación de costo ligada a una cotización",
	"cotizacion_interna.aprobada": "Estimación de costo aprobada",
	"cotizacion_interna.rechazada": "Estimación de costo rechazada",
	"factura.create": "Factura emitida",
	"factura.cancel": "Factura cancelada",
	"factura.timbrar": "Factura timbrada ante el SAT",
	"factura.cancelar_sat": "Cancelación solicitada al SAT",
	"nota_venta.create": "Nota de venta creada",
	"nota_venta.cancel": "Nota de venta cancelada",
	"nota_venta.facturar": "Nota de venta convertida en factura",
	"cliente.pac_link": "Cliente vinculado con el proveedor de timbrado",

	// Ajustes del sistema. The entry records WHICH settings moved and, for a secret, only whether
	// one now exists — never a value, never a hint. The audit trail must never become a way to
	// obtain access (Rule 3).
	"ajuste.update": "Ajustes del sistema actualizados",
	"empresa.update": "Información de contacto de la empresa actualizada",
	"cuenta_bancaria.create": "Cuenta bancaria dada de alta",
	"cuenta_bancaria.update": "Cuenta bancaria actualizada",
	"cuenta_bancaria.archive": "Cuenta bancaria archivada",
	"permiso.actualizar": "Registro de permisos actualizado",
	"pago.register": "Pago registrado",
	"cliente.credito": "Condiciones de crédito actualizadas",
	"cliente.credito_override": "Venta a crédito autorizada sobre el límite",
	"canal.vinculacion_generada": "Código de vinculación de canal generado",
	"canal.vinculado": "Cuenta vinculada a WhatsApp/Telegram",
	"canal.desvinculado": "Cuenta desvinculada de un canal",
	"canal.conversacion_tomada": "Conversación de canal tomada por un humano",
	"canal.conversacion_regresada": "Conversación de canal regresada al bot",
} as const satisfies Record<string, string>;

export type AuditAction = keyof typeof AUDIT_ACTIONS;

/** Entities that appear in the log, derived from the action keys. */
export const AUDIT_ENTITIES = [...new Set(Object.keys(AUDIT_ACTIONS).map((key) => key.split(".")[0]))] as string[];

export const auditActionLabel = (action: string): string => (AUDIT_ACTIONS as Record<string, string>)[action] ?? action;
